### ISSUE TITLE
set up  Kanban board

### ISSUE THREAD

**Issue by muneeb3123** [muneeb3123/ruby-capstone#34]
This issue includes:

- Create an empty repository for your group project.

- Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in order to copy the [[TEMPLATE] Ruby Group Capstone Project](https://github.com/microverseinc/curriculum-ruby/projects/1) board.
- Open the GitHub project (Kanban board) in your team repo.
- Open [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md) and read them carefully.

- Open [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) and compare it with the [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md).

- Create tasks on your Kanban board based on the [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md).

- Each task should be a separate card that:
Has a descriptive title.
Has the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of estimated work. You shouldn't change the points after dividing up cards, even if the actual work takes longer.
Has a description of the task.
Each of the team members should assign themselves to the cards as divided in the [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.

**In this project we are 3 team members**

-  Team member 1:   @muneeb3123  
-  Team member 2:  @flemton  
-  Team member 3:     @LarryIVC 

 

- Github Project Link :https://github.com/muneeb3123/ruby-capstone/projects/2

**Comment by Gambit142** [comment]
Hi @muneeb3123 @flemton @LarryIVC 👋, 

Good job so far!

## Highlights
- Created a kanban board that is identical to the sample ✔️ 
- Tasks are distributed in a fair way ✔️ 
- Each card has a title, description and point ✔️ 
- Each card is assigned to a member based on the project's requirements ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

- [x] I noticed that each member's `Add Unit Tests` card contains the task for creating options in the console in the description of the card. I would advise you to edit them out of the description of the `Add Unit Tests` card and create a card for them with the appropriate description 👍 😎 . 

### Student A

![image](https://github.com/muneeb3123/ruby-capstone/assets/77106962/6fde0876-8581-46f4-8c50-e380b2f61c90)

### Student B

![image](https://github.com/muneeb3123/ruby-capstone/assets/77106962/4d50a1ce-3703-481e-88d0-e4ca4b3c3c61)

### Student C

![image](https://github.com/muneeb3123/ruby-capstone/assets/77106962/1220a710-a0fb-4ed4-a44b-95159ec3dd38)



Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by LarryIVC** [comment]
Thanks @Gambit142, for your feedback, We correct it.

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @muneeb3123, @LarryIVC and @flemton👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
